name       : swipl
version    : 7.4.2
release    : 1
source     :
    - http://www.swi-prolog.org/download/stable/src/swipl-7.4.2.tar.gz : 7f17257da334bc1e7a35e9cf5cb8fca01d82f1ea406c7ace76e9062af8f0df8b
license    : BSD-3-Clause
component  : programming
summary    : SWI-Prolog offers a comprehensive free Prolog environment
description: |
    SWI-Prolog is a versatile implementation of the Prolog language. Its robust multi-threading, extended data types, unbounded arithmetic and Unicode representation of text allow for natural representation of documents (e.g., XML, JSON, RDF) and exchange of data with other programming paradigms.
builddeps  :
    - pkgconfig(libarchive)
    - pkgconfig(libedit)
    - pkgconfig(libpcre2-posix)
    - pkgconfig(libunwind)
    - pkgconfig(xext)
    - pkgconfig(xft)
    - pkgconfig(xinerama)
    - pkgconfig(xpm)
    - pkgconfig(xt)
    - libjpeg-turbo-devel
    - unixodbc-devel
setup      : |
    %configure --disable-static \
               --enable-shared \
               --with-world
build      : |
    %make
install    : |
    %make_install
