name       : swipl
version    : 7.6.4
release    : 2
source     :
    - http://www.swi-prolog.org/download/stable/src/swipl-7.6.4.tar.gz : 2d3d7aabd6d99a02dcc2da5d7604e3500329e541c6f857edc5aa06a3b1267891
license    : BSD-3-Clause
component  : programming
summary    : SWI-Prolog offers a comprehensive free Prolog environment
description: |
    SWI-Prolog is a versatile implementation of the Prolog language. Its robust multi-threading, extended data types, unbounded arithmetic and Unicode representation of text allow for natural representation of documents (e.g., XML, JSON, RDF) and exchange of data with other programming paradigms.
builddeps  :
    - pkgconfig(libarchive)
    - pkgconfig(libedit)
    - pkgconfig(libjpeg)
    - pkgconfig(libpcre2-posix)
    - pkgconfig(libunwind)
    - pkgconfig(xext)
    - pkgconfig(xft)
    - pkgconfig(xinerama)
    - pkgconfig(xpm)
    - pkgconfig(xt)
    - unixodbc-devel
setup      : |
    %configure --disable-static \
               --enable-shared \
               --with-world
build      : |
    %make
install    : |
    %make_install
